### ISSUE TITLE
なぞなぞツイートについて

### ISSUE THREAD

**Issue by daruma3940** [kagetsu-claire/IzuminShogiBot#1]
こんにちは。将棋ソフトを開発している大石泉bot 楽しく拝見させていただいております。
なぞなぞを作ってみたのですがツイートのネタにいかがでしょうか。
https://github.com/daruma3940/nazonazo/blob/master/idol/nazonzo2.jpg

**Comment by daruma3940** [comment]
わかりにくかったと思われる箇所をわかりやすくしてみました
https://github.com/daruma3940/nazonazo/blob/master/idol/nazonzo3.jpg

**Comment by KagetsuClaire** [comment]
#答えが分かったら答えを書かずにRT
でいいかな？

**Comment by daruma3940** [comment]
良いと思います！

**Comment by KagetsuClaire** [comment]
了解！
あとnazonazoじゃなくて、nazonzoなのはわざと？typo？

**Comment by daruma3940** [comment]
あっtypoです(´・ω・｀)
でも修正をするほどのことでも無いと思うのでこのままにすると思います(´・ω・｀)

**Comment by KagetsuClaire** [comment]
今、調べてて気になったんですけど、
このタグ（#答えが分かったら答えを書かずにRT）、nodchipさんが最初に始めたタグみたいで、
nodchipさん1人しか使ってないですが、検索する人の邪魔にならないですかね。
別タグ作ったほうがいいですかね(´・ω・｀)

**Comment by KagetsuClaire** [comment]
まあ、nodchipさんだけ検索したけりゃ、
from:nodchipってすればいい話かもしれないけど

**Comment by daruma3940** [comment]
![ws000020](https://cloud.githubusercontent.com/assets/17908723/21427157/320a7656-c896-11e6-80b0-94c51345f31a.JPG)
他にも使われている方を見つけたので大丈夫だとは思うのですが...別のタグを作ったほうがご迷惑をおかけしないかもしれませんね(´・ω・｀)
私は別にこのタグを使っても良いと思っていますが

**Comment by KagetsuClaire** [comment]
私も基本的には自由だと思いますし、許可を取るようなものでもないと思いますけど……
まあ気にしすぎですかね(´・ω・｀)
では、早速アップします。
（答えを書かずにRTだと正解に反応する自動リプライ機能を付けなくていいから便利ｗ）

**Comment by daruma3940** [comment]
ありがとうございます！
お願いします！
